### ISSUE TITLE
sharedInbox issues

### ISSUE THREAD

**Issue by puckipedia** [litepub/litepub#1]
" If an actor has a `sharedInbox` property, then an implementation MAY choose to deliver the message to the `sharedInbox` instead of directly to the actor's inbox."

how does this interact with unknown audiences (e.g. delivering to a collection which the receiving server can't see, or `bcc`/`bto`)?

**Comment by kaniini** [comment]
litepub is s2s only.

**Comment by puckipedia** [comment]
I am a server. I want to tell another server "hey, this person got this message". this collection is in (b)cc and contains, say, a thousand people, which is a subset of a user's followers. how do? this does not touch any c2s stuffs, I was actually working on implementing this in Mastodon, where you would just choose a circle of followers to send the post to. your spec seems to imply I can always replace inbox with sharedInbox (which BTW, is not in the root of the actor but in endpoints)

**Comment by kaniini** [comment]
bcc/bto are not allowed in ActivityPub S2S.  if the implementation explicitly wants the side effects of delivering to a non-shared inbox, then they may also do that.  hince why it says MAY choose to deliver the message to the `sharedInbox`.
