### ISSUE TITLE
[RFC] Disable Comments/Replies

### ISSUE THREAD

**Issue by dansup** [litepub/litepub#3]
### ~~Proposal~~
~~Add ```"commentsDisabled": "as:commentsDisabled"``` extension, with a boolean value that describes the state of accepting/displaying comments or replies.~~

~~Due to the nature of ActivityPub and existing implementations, I think this is a good first step towards a long term goal of OCAP that could replace the extension.~~

I think this is a better idea https://github.com/tootsuite/mastodon/issues/8565#issuecomment-481525368

**Comment by kaniini** [comment]
How would this be a good first step toward supporting OCAP?  It seems informational at best.

**Comment by jalcine** [comment]
@dansup For the sake of history and discoverability, I don't think it's a good idea to edit things away. Granted, GitHub gives us history but I don't think that's indexed. It might help others in the future who has similar questions.
