### ISSUE TITLE
Status and LICENSE question

### ISSUE THREAD

**Issue by aschrijver** [litepub/litepub#6]
I am creating a new _developer resources_ page for the [Feneas wiki research area](https://git.feneas.org/feneas/fediverse/-/wikis/Home) and noticed that your project has no LICENSE. Website is down, so I can't check there.

Also since there haven't been recent commits, I would like to inform about status and future plans.

(**Edit**: Updated as this is a spec, not a code repo. Too quick in copy/paste, sorry)

**Comment by kaniini** [comment]
for the most part litepub group folded back into SocialCG.

there is nothing here that is licensable.

**Comment by aschrijver** [comment]
Thanks, I have updated status on the [new page](https://git.feneas.org/feneas/fediverse/-/wikis/Watchlist-for-ActivityPub-developer-resources#protocol-specifications) I just created.
